#!/bin/bash

export DOCKER_HOST=${DOCKER_HOST:=unix:///var/run/docker.sock}

cmd-test() {
	echo test
}

cmd-build() {
	echo build
}

cmd-status() {
	echo status
}

cmd-down() {
	echo down
}

cmd-up() {
	echo up
}

cmd-configure() {
	echo configure
}

usage() {
cat <<EOF
Usage:
bim test
bim build
bim status
bim down
bim up
bim help
EOF
	exit 1
}


main() {
	case "$1" in
	test)					      shift; cmd-test; $@;;
	build)              shift; cmd-build $@;;
	status)             shift; cmd-status $@;;
	down)               shift; cmd-down $@;;
	configure)          shift; cmd-configure $@;;
	up)                 shift; cmd-up $@;;
	help)               shift; usage $@;;
	*)                  usage $@;;
	esac
}

main "$@"
