#!/bin/bash

export DOCKER_HOST=${DOCKER_HOST:=unix:///var/run/docker.sock}

cmd-test() {
	case "$1" in
	all)
		cmd-test unit
		cmd-test integration
		cmd-test acceptance
;;
unit)
		echo "unit tests"
;;
integration)
		echo "integration tests"
;;
acceptance)
		bats --tap test/vagrant
;;
	*)
		usage test
;;
	esac
}

cmd-build() {
	echo build
}

cmd-status() {
	echo status
}

cmd-down() {
	echo down
}

cmd-up() {
	echo up
}

cmd-configure() {
	echo configure
}

usage() {
	case "$1" in
	test)
cat <<EOF
Usage:
bim test <all|acceptance|integration|unit>
EOF
;;
	*)
cat <<EOF
Usage:
bim test <all|acceptance|integration|unit>
bim build
bim status
bim down
bim up
bim help [command]
EOF
;;
	esac
}

main() {
	case "$1" in
	test)					      shift; cmd-test $@;;
	build)              shift; cmd-build $@;;
	status)             shift; cmd-status $@;;
	down)               shift; cmd-down $@;;
	configure)          shift; cmd-configure $@;;
	up)                 shift; cmd-up $@;;
	help)               shift; usage $@;;
	*)                  usage $@;;
	esac
}

main "$@"
